### ISSUE TITLE
Versioning decisions

### ISSUE THREAD

**Issue by Pedals2Paddles** [OpenSolo/meta-3dr#1]
We need to decide on a versioning scheme for release open solo to the masses.  It's important, and it ensure the controller and solo are operating the same compatible versions.  It also will distinguish between people's custom tinkering, and real tested releases.

We also unfortunately need to distinguish between releases for the stock solo and Solo's with the Green Cube running master. The only difference between the two would be the ArduCopter version it contains.  The old ArduCopter-Solo for the stock cubes and ArduCopter 3.5.x for the green cubes.  The rest of the FW for the IMX and artoo is the same.

The last 3DR complete release was 2.4.2

**Suggestions:**

* I think we should start our own versioning with 1.0.0 rather than continuing where 3DR left off. That will avoid any and all ambiguity.

* To distinguish between stock solos and green cube solos, I suggest appending the color to the version name

* Our first release would look like **Open Solo v1.0.0 Green** for the green cube solos. It would contain ArduCopter 3.5.2.  Then **Open Solo v1.0.0 Black** would be for the stock solos and contain the old ArduCopter-Solo version.

**Comment by peterbarker** [comment]
On Wed, 23 Aug 2017, Matt wrote:

>     I think we should start our own versioning with 1.0.0 rather than
>     continuing where 3DR left off. That will avoid any and all ambiguity.

Sounds good.  Are we ready for 1.0.0, though? :-)

>     To distinguish between stock solos and green cube solos, I suggest
>     appending the color to the version name

Sounds good.  Will give us another place to explain what the Green is all 
about, which is good.

**Comment by Pedals2Paddles** [comment]
Definitely not ready for 1.0.0 yet.  I might have something for people to beta test by this weekend, but I don't think I'd call anything 1.0.0 until it is beta tested and merged into master.

**Comment by davidbuzz** [comment]
We can't go backward below the existing 3dr version number/s because the 3dr solo phone app will have a schism. so 0.0.x and 1.x.x are both off the table. opensolo internal version numbers need to be above 2.4.2.
The team also made the decision that both controller and solo must be flashed together, so they can put matching version/s in both, which means we don't need to match any specific 3dr version numbers for compatibility. ( so using a 3dr flashed "stock" controller, and an opensolo flashed drone is not a supported setup ).
Typical versioning semantic/s suggests that changes breaking backward compatibility should increment the first number in the triple, so the suggestion currently is that we do our internal versioning starting from 3.0.0
( aside: Beta releases are a slightly different matter, as the version triple doesn't support extensions like -rc1 , so it will mean that beta releases should be numbered slightly less than the expected final release numbering, so will be called ( eg ) 2.9.9x  for a 3.0 release or 2.4.9x for a 3.0 release.  )
